# Telegram配置示例
# 请复制此文件为telegram_config.yml并修改为你的配置

# Bot Token，从BotFather获取
# 例如：7492770499:AAEIxmX_pGDGL5ORTOB5E2u-8_9KYC2a-NA
bot_token: "7492770499:AAEIxmX_pGDGL5ORTOB5E2u-8_9KYC2a-NA"

# Chat ID，接收消息的目标ID
# 可以是私聊ID（正数，如123456789）
# 频道ID（负数，如-1001234567890，或@channel_name）
# 群组ID（负数，如-123456789）
chat_id: "723610835"

# 消息解析模式，支持HTML、Markdown或留空（纯文本）
# HTML格式支持：<b>粗体</b>、<i>斜体</i>、<code>等宽字</code>等标签
# Markdown格式支持：*粗体*、_斜体_、`等宽字`等
parse_mode: "HTML"

# 消息队列配置
# 批量发送大小（每次处理的消息数量）
batch_size: 1

# 是否启用消息去重
deduplicate: true 